[tool.poetry]
name = "gpt2-tamil"
version = "0.1.0"
description = ""
authors = ["JINO-ROHIT <find.jinorohit@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
sentencepiece = "^0.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
